export const SUPPORTED_LANGUAGES = [
  "Abkhazian", "Acehnese", "Afrikaans", "Akan", "Albanian", "Amharic", "Arabic", "Armenian", "Assamese", "Avaric", "Awadhi", "Aymara", "Azerbaijani",
  "Balinese", "Bambara", "Bashkir", "Basque", "Batak Karo", "Batak Simalungun", "Batak Toba", "Belarusian", "Bemba", "Bengali", "Betawi", "Bhojpuri", "Bikol", "Bislama", "Bosnian", "Breton", "Buginese", "Bulgarian", "Burmese",
  "Cantonese", "Catalan", "Cebuano", "Central Kurdish (Sorani)", "Chamorro", "Chechen", "Chhattisgarhi", "Chichewa (Nyanja)", "Chittagonian", "Chukchi", "Chuvash", "Cornish", "Corsican", "Crimean Tatar (Cyrillic)", "Crimean Tatar (Latin)", "Croatian", "Czech",
  "Danish", "Dari", "Dhivehi", "Dogri", "Dutch", "Dyula", "Dzongkha",
  "English", "Esperanto", "Estonian", "Ewe",
  "Faroese", "Fijian", "Filipino (Tagalog)", "Finnish", "French", "French (Canada)", "Frisian", "Friulian", "Fula (Fulah)",
  "Galician", "Ganda (Luganda)", "Georgian", "German", "Greek", "Guarani", "Gujarati",
  "Haitian Creole", "Hausa", "Hawaiian", "Hebrew", "Hiligaynon", "Hindi", "Hmong", "Hunsrik", "Hungarian",
  "Iban", "Icelandic", "Igbo", "Ilocano", "Indonesian", "Inuktitut (Latin)", "Inuktitut (Syllabics)", "Irish", "Italian",
  "Jamaican Patois", "Japanese", "Javanese", "Jingpo (Kachin)",
  "Kannada", "Kapampangan", "Kazakh", "Khasi", "Khmer", "Kinyarwanda", "Konkani", "Korean", "Krio", "Kurdish (Kurmanji)", "Kyrgyz",
  "Lao", "Latin", "Latgalian", "Latvian", "Ligurian", "Limburgish", "Lingala", "Lithuanian", "Lombard", "Luganda", "Luxembourgish",
  "Macedonian", "Madurese", "Maithili", "Malagasy", "Malay", "Malay (Jawi)", "Malayalam", "Maltese", "Manx", "Maori", "Marathi", "Marshallese", "Marwari", "Mauritian Creole", "Mayan (Yucatec Maya)", "Meitei (Manipuri)", "Mizo", "Mongolian",
  "Navajo (Eastern Huasteca Nahuatl)", "Ndau", "Ndebele (South)", "Nepali", "Nepali (Newari)", "Northern Kurdish (Kurmanji)", "Northern Sami", "Norwegian",
  "Occitan", "Odia (Oriya)", "Oromo", "Ossetian",
  "Pampanga (Kapampangan)", "Pangasinan", "Papiamento", "Pashto", "Persian (Farsi)", "Polish", "Portuguese (Brazil)", "Portuguese (Portugal)", "Punjabi (Gurmukhi)", "Punjabi (Shahmukhi)",
  "Quechua",
  "Romanian", "Romansh", "Rundi (Kirundi)", "Russian",
  "Sango", "Sanskrit", "Santali (Latin)", "Santali (Ol Chiki)", "Scottish Gaelic", "Serbian", "Seychellois Creole", "Shan", "Shona", "Sicilian", "Silesian", "Sindhi", "Sinhala", "Slovak", "Slovenian", "Somali", "Southern Sotho (Sesotho)", "Spanish", "Sundanese", "Swahili", "Swati", "Swedish",
  "Tahitian", "Tajik", "Tamasheq", "Tamasheq (Tifinagh)", "Tamil", "Tatar", "Telugu", "Tetum", "Thai", "Tibetan", "Tigrinya", "TongAN", "Tsonga", "Tswana", "Turkish", "Turkmen", "Tuvan",
  "Udmurt", "Ukrainian", "Urdu", "Uyghur", "Uzbek",
  "Venetian", "Vietnamese",
  "Waray", "Welsh", "Wolof",
  "Xhosa",
  "Yakut (Sakha)", "Yiddish", "Yoruba",
  "Zhuang (Chuáng)", "Zulu"
];
